name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        id: build
        uses: ./.github/actions/buildAction

      - name: Show APK path
        run: echo "APK path is ${{ steps.build.outputs.apk-path }}"
